apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-claim
  namespace: testing
spec:
  accessModes:
    - ReadWriteOnce
  #storageClassName: ebs-sc
  storageClassName: gp2
  resources:
    requests:
      storage: 4Gi