
podTemplate(cloud: 'dev-kube', serviceAccount: 'jenkins-admin', 
            yaml: readTrusted('pipeline/jenkins/agent/pod.yaml'),
            envVars: [
                envVar(key: 'PETCLINIC_HOME', value: '/home/jenkins/agent/workspace/petclinic'),
                envVar(key: 'DOCKER_ID', value: 'agdgpn'),
                envVar(key: 'CONFIG_DOCKER_IMAGE', value: 'config'),
                envVar(key: 'DISCOVERY_DOCKER_IMAGE', value: 'discovery'),
                envVar(key: 'CUSTOMERS_DOCKER_IMAGE', value: 'customers'),
                envVar(key: 'VETS_DOCKER_IMAGE', value: 'vets'),
                envVar(key: 'VISITS_DOCKER_IMAGE', value: 'visits'),
                envVar(key: 'ADMIN_DOCKER_IMAGE', value: 'admin'),
                envVar(key: 'APIGATEWAY_DOCKER_IMAGE', value: 'api-gateway'),
                envVar(key: 'DOCKER_TAG', value: 'v.${BUILD_ID}.0')
            ]) {
    node(POD_LABEL) {
        stage('Docker Build Test images') {
            container('docker') {
                sh '''
                ls
                sh scripts/devops/build_image.sh $CONFIG_DOCKER_IMAGE local
                sh scripts/devops/build_image.sh $DISCOVERY_DOCKER_IMAGE local
                sh scripts/devops/build_image.sh $CUSTOMERS_DOCKER_IMAGE local
                sh scripts/devops/build_image.sh $VETS_DOCKER_IMAGE local
                sh scripts/devops/build_image.sh $VISITS_DOCKER_IMAGE local
                sh scripts/devops/build_image.sh $ADMIN_DOCKER_IMAGE local
                sh scripts/devops/build_image.sh $APIGATEWAY_DOCKER_IMAGE local
                '''   
            }
        }
    }
}