apiVersion: v1
kind: Pod
spec:
  containers:
  - name: jnlp
    image: jenkins/inbound-agent:latest
  - name: kubectl
    image: amaceog/kubectl
    #image: bitnami/kubectl:1.25
    command:
    - cat
    tty: true
    resources:
      requests:
        memory: "2Gi"
        cpu: "250m"
      limits:
        memory: "3Gi"
        cpu: "300m"
  - name: helm
    image: alpine/helm:3.11.1
    command:
    - cat
    tty: true
    resources:
      requests:
        memory: "300Mi"
        cpu: "100m"
      limits:
        memory: "500Mi"
        cpu: "300m"
  - name: docker
    image: docker
    command:
    - cat
    tty: true
    volumeMounts:
    - name: dockersock
      mountPath: /var/run/docker.sock
  volumes:
  - name: dockersock
    hostPath:
      path: /var/run/docker.sock