/*
* PIPELINE PROD : rataché à la branche master (mise en preprod puis en prod)
*/
pipeline { 
    environment
    {
        DOCKER_TAG = "prod-v.${BUILD_ID}.0"
        DOCKER_PASS = credentials("DOCKER_HUB_PASS")
        NS = 'prod'
        MIDDLEWARE_NS = 'kube-system'
    }                
    agent {
        kubernetes {
            cloud 'prod-kube'
            yamlFile 'pipeline/jenkins/agent/prod/pod.yaml'
            serviceAccount 'jenkins-admin'
            namespace "prod"
        }
    }
    stages {
        stage('Build Config for prod') {
            when { changeset "spring-petclinic-config-server/**" }
            steps {
                container('docker') {
                    sh '''
                    sh scripts/devops/build_image.sh $CONFIG_DOCKER_IMAGE dockerhub $DOCKER_ID $DOCKER_TAG
                    '''
                }
            }
        }
        stage('Build Discovery for prod') {
            when { changeset "spring-petclinic-discovery-server/**" }
            steps {
                container('docker') {
                    sh '''
                    sh scripts/devops/build_image.sh $DISCOVERY_DOCKER_IMAGE dockerhub $DOCKER_ID $DOCKER_TAG
                    '''
                }
            }
        }
        stage('Build Cusmomers for prod') {
            when { changeset "spring-petclinic-customers-service/**" }
            steps {
                container('docker') {
                    sh '''
                    sh scripts/devops/build_image.sh $CUSTOMERS_DOCKER_IMAGE dockerhub $DOCKER_ID $DOCKER_TAG
                    '''
                }
            }
        }
        stage('Build Vets for prod') {
            when { changeset "spring-petclinic-vets-service/**" }
            steps {
                container('docker') {
                    sh '''
                    sh scripts/devops/build_image.sh $VETS_DOCKER_IMAGE dockerhub $DOCKER_ID $DOCKER_TAG
                    '''
                }
            }
        }
        stage('Build Visits for prod') {
            when { changeset "spring-petclinic-visits-service/**" }
            steps {
                container('docker') {
                    sh '''
                    sh scripts/devops/build_image.sh $VISITS_DOCKER_IMAGE dockerhub $DOCKER_ID $DOCKER_TAG
                    '''
                }
            }
        }
        
        stage('Build Admin for prod') {
            when { changeset "spring-petclinic-admin-server/**" }
            steps {
                container('docker') {
                    sh '''
                    sh scripts/devops/build_image.sh $ADMIN_DOCKER_IMAGE dockerhub $DOCKER_ID $DOCKER_TAG
                    '''
                }
            }
        }
        stage('Build Api-gateway for prod') {
            when { changeset "spring-petclinic-api-gateway/**" }
            steps {
                container('docker') {
                    sh '''
                    sh scripts/devops/build_image.sh $APIGATEWAY_DOCKER_IMAGE dockerhub $DOCKER_ID $DOCKER_TAG
                    '''
                }
            }
        }
        stage('Push Config image for prod') {
            when { changeset "spring-petclinic-config-server/**" }
            steps {
                container('docker') {
                    sh '''
                    docker login -u $DOCKER_ID -p $DOCKER_PASS
                    docker push $DOCKER_ID/$CONFIG_DOCKER_IMAGE-image:$DOCKER_TAG
                    '''
                }
            }
        }
        stage('Push Discovery image for prod') {
            when { changeset "spring-petclinic-discovery-server/**" }
            steps {
                container('docker') {
                    sh '''
                    docker login -u $DOCKER_ID -p $DOCKER_PASS
                    docker push $DOCKER_ID/$DISCOVERY_DOCKER_IMAGE-image:$DOCKER_TAG
                    '''
                }
            }
        }
        stage('Push Customers image for prod') {
            when { changeset "spring-petclinic-customers-service/**" }
            steps {
                container('docker') {
                    sh '''
                    docker login -u $DOCKER_ID -p $DOCKER_PASS
                    docker push $DOCKER_ID/$CUSTOMERS_DOCKER_IMAGE-image:$DOCKER_TAG
                    '''
                }
            }
        }
        stage('Push Vets image for prod') {
            when { changeset "spring-petclinic-vets-service/**" }
            steps {
                container('docker') {
                    sh '''
                    docker login -u $DOCKER_ID -p $DOCKER_PASS
                    docker push $DOCKER_ID/$VETS_DOCKER_IMAGE-image:$DOCKER_TAG
                    '''
                }
            }
        }
        stage('Push Visits image for prod') {
            when { changeset "spring-petclinic-visits-service/**" }
            steps {
                container('docker') {
                    sh '''
                    docker login -u $DOCKER_ID -p $DOCKER_PASS
                    docker push $DOCKER_ID/$VISITS_DOCKER_IMAGE-image:$DOCKER_TAG
                    '''
                }
            }
        }
        stage('Push Admin image for prod') {
            when { changeset "spring-petclinic-admin-server/**" }
            steps {
                container('docker') {
                    sh '''
                    docker login -u $DOCKER_ID -p $DOCKER_PASS
                    docker push $DOCKER_ID/$ADMIN_DOCKER_IMAGE-image:$DOCKER_TAG
                    '''
                }
            }
        }
        stage('Push Api-Gateway image for prod') {
            when { changeset "spring-petclinic-api-gateway/**" }
            steps {
                container('docker') {
                    sh '''
                    docker login -u $DOCKER_ID -p $DOCKER_PASS
                    docker push $DOCKER_ID/$APIGATEWAY_DOCKER_IMAGE-image:$DOCKER_TAG
                    '''
                }
            }
        }

        // Déploiement de MYSQL sur l'environnement de TESTING si pas encore fait.
        stage('Check/install MySQL image for prod'){
            steps {
                container('helm') { 
                    script {
                        try {
                            sh '''
                            # Mysql deployment if its not already deployed
                            helm status mysql-server -n testing
                            '''
                        } catch (err) {
                            echo "Message: ${err}"
                            echo "Deploying mysql in testing ns .."
                            sh '''
                            cp kubernetes/helm/mysql-server/values.yaml values.yml
                            helm upgrade --install mysql-server kubernetes/helm/mysql-server --values=values.yml --create-namespace --namespace testing 
                            '''
                        }
                    }
                }
            }
        }
        
        stage('Deploy Config app in prod') {
            when { changeset "spring-petclinic-config-server/**" }
            steps {
                container('helm') { 
                    sh '''
                    # Config Server deployment
                    cp kubernetes/helm/config-server/values.yaml values.yml
                    sed -i "s+tag.*+tag: ${DOCKER_TAG}+g" values.yml                    
                    helm upgrade --install config-server kubernetes/helm/config-server --values=values.yml --create-namespace --namespace $NS
                    '''
                }
            }
        }
        stage('Deploy Discovery app in prod') {
            when { changeset "spring-petclinic-discovery-server/**" }
            steps {
                container('helm') { 
                    sh '''
                    # Discovery Server deployment
                    cp kubernetes/helm/discovery-server/values.yaml values.yml
                    sed -i "s+tag.*+tag: ${DOCKER_TAG}+g" values.yml
                    helm upgrade --install discovery-server kubernetes/helm/discovery-server --values=values.yml --create-namespace --namespace $NS
                    '''
                }
            }
        }
        stage('Deploy Customers app in prod') {
            when { changeset "spring-petclinic-customers-service/**" }
            steps {
                container('helm') { 
                    sh '''
                    # Customers Service deployment
                    cp kubernetes/helm/customers-service/values.yaml values.yml
                    sed -i "s+tag.*+tag: ${DOCKER_TAG}+g" values.yml                    
                    helm upgrade --install customers-service kubernetes/helm/customers-service --values=values.yml --create-namespace --namespace $NS
                    '''
                }
            }
        }
        stage('Deploy Vets app in prod') {
            when { changeset "spring-petclinic-vets-service/**" }
            steps {
                container('helm') { 
                    sh '''
                    # Vets Service deployment
                    cp kubernetes/helm/vets-service/values.yaml values.yml
                    sed -i "s+tag.*+tag: ${DOCKER_TAG}+g" values.yml                    
                    helm upgrade --install vets-service kubernetes/helm/vets-service --values=values.yml --create-namespace --namespace $NS
                    '''
                }
            }
        }
        stage('Deploy Visits app in prod') {
            when { changeset "spring-petclinic-visits-service/**" }
            steps {
                container('helm') { 
                    sh '''
                    # Visits Service deployment
                    cp kubernetes/helm/visits-service/values.yaml values.yml
                    sed -i "s+tag.*+tag: ${DOCKER_TAG}+g" values.yml                    
                    helm upgrade --install visits-service kubernetes/helm/visits-service --values=values.yml --create-namespace --namespace $NS
                    '''
                }
            }
        }
        stage('Deploy Admin app in prod') {
            when { changeset "spring-petclinic-admin-server/**" }
            steps {
                container('helm') { 
                    sh '''
                    # Visits Service deployment
                    cp kubernetes/helm/admin-server/values.yaml values.yml
                    sed -i "s+tag.*+tag: ${DOCKER_TAG}+g" values.yml                    
                    helm upgrade --install admin-server kubernetes/helm/admin-server --values=values.yml --create-namespace --namespace $NS
                    '''
                }
            }
        }
        stage('Deploy Api-gateway app in prod') {
            when { changeset "spring-petclinic-api-gateway/**" }
            steps {
                container('helm') { 
                    sh '''
                    # Visits Service deployment
                    cp kubernetes/helm/api-gateway/values.yaml values.yml
                    sed -i "s+tag.*+tag: ${DOCKER_TAG}+g" values.yml   
                    sed -i "s+traefik.ingress.kubernetes.io/router.middlewares.*+traefik.ingress.kubernetes.io/router.middlewares: $MIDDLEWARE_NS-services-strip@kubernetescrd+g" kubernetes/helm/api-gateway/templates/ingress.yaml 
                    cat kubernetes/helm/api-gateway/templates/ingress.yaml                 
                    helm upgrade --install api-gateway kubernetes/helm/api-gateway --values=values.yml --create-namespace --namespace $NS
                    '''
                }
            }
        }
        stage('Api-gateway accessibility in prod') {
            steps {
                    sh '''
                    sleep 20
                    ./scripts/devops/test_accessibilite.sh http://pn-macos-vb-ubuntu/
                    '''
            }
        }
    }
}

 
                   