apiVersion: v1
kind: Pod
metadata:
  name: dock
spec:
  containers:
  - name: docker
    image: docker
    #image: bentolor/docker-dind-awscli
    env:
    - name: PETCLINIC_HOME
      value: "/home/jenkins/agent/workspace/petclinic-testing"
    - name: DOCKER_ID
      value: "agdgpn"
    - name: CONFIG_DOCKER_IMAGE
      value: "config"
    - name: DISCOVERY_DOCKER_IMAGE
      value: "discovery"
    - name: CUSTOMERS_DOCKER_IMAGE
      value: "customers"
    - name: VETS_DOCKER_IMAGE
      value: "vets"
    - name: VISITS_DOCKER_IMAGE
      value: "visits"
    - name: ADMIN_DOCKER_IMAGE
      value: "admin"
    - name: APIGATEWAY_DOCKER_IMAGE
      value: "api-gateway"
    command:
    - cat
    tty: true
    volumeMounts:
    - name: dockersock
      mountPath: /var/run/docker.sock
  volumes:
  - name: dockersock
    #persistentVolumeClaim:
    #  claimName: ebs-claim
    hostPath:
      path: /var/run/docker.sock