/*
* PIPELINE TESTING : rataché à la branche dev (développement)
*/
pipeline { 
    environment
    {
        PETCLINIC_HOME = "/home/jenkins/agent/workspace/petclinic-testing" 
        DOCKER_ID = "agdgpn" 
        CONFIG_DOCKER_IMAGE = "config"
        DISCOVERY_DOCKER_IMAGE = "discovery"
        CUSTOMERS_DOCKER_IMAGE = "customers"
        VETS_DOCKER_IMAGE = "vets"
        VISITS_DOCKER_IMAGE = "visits"
        ADMIN_DOCKER_IMAGE = "admin"
        APIGATEWAY_DOCKER_IMAGE = "api-gateway"
        DOCKER_TAG = "testing-v.${BUILD_ID}.0"                            // Tag build images
        DOCKER_PASS = credentials("DOCKER_HUB_PASS")                      // Token dockerhub stocké dans jenkins master
        NS = 'testing'                                                    // Namespace environnement cible
        MIDDLEWARE_NS = 'traefik'                                     // Namespace du middleware
        AWS_MYSQL_RDS = "petclinic-testing-database.cljowf4o15oe.eu-west-3.rds.amazonaws.com"
    }                
    agent {
        kubernetes {
            cloud 'testing-kube'
            yamlFile 'pipeline/jenkins/agent/pod.yaml'
            serviceAccount 'jenkins-admin'
            namespace "testing"
        }
    }
    stages {
        stage('Build config & discovery'){
            parallel {
                stage('Build Config image for testing') {
                    when { changeset "spring-petclinic-config-server/**" }
                    agent { label "docker-agent-a" }
                    steps {
                        sh '''
                        ./scripts/devops/build_image.sh $CONFIG_DOCKER_IMAGE dockerhub $DOCKER_ID $DOCKER_TAG
                        '''
                    }
                }
                stage('Build Discovery image for testing') {
                    when { changeset "spring-petclinic-discovery-server/**" }
                    agent { label "docker-agent-b" }
                    steps {
                        sh '''
                        sh scripts/devops/build_image.sh $DISCOVERY_DOCKER_IMAGE dockerhub $DOCKER_ID $DOCKER_TAG
                        '''
                    }
                }
            }
        }
        stage('Build customers & vets'){
            parallel{
                stage('Build Cusmomers image for testing') {
                    when { changeset "spring-petclinic-customers-service/**" }
                    agent { label "docker-agent-a" }
                    steps {
                        sh '''
                        sh scripts/devops/build_image.sh $CUSTOMERS_DOCKER_IMAGE dockerhub $DOCKER_ID $DOCKER_TAG
                        '''
                    }
                }
                stage('Build Vets image for testing') {
                    when { changeset "spring-petclinic-vets-service/**" }
                    agent { label "docker-agent-b" }
                    steps {
                        sh '''
                        sh scripts/devops/build_image.sh $VETS_DOCKER_IMAGE dockerhub $DOCKER_ID $DOCKER_TAG
                        '''
                    }
                }
            }
        }
        stage('Build visits & api-gateway'){
            parallel{
                stage('Build Visits image for testing') {
                    when { changeset "spring-petclinic-visits-service/**" }
                    agent { label "docker-agent-a" }
                    steps {
                        sh '''
                        sh scripts/devops/build_image.sh $VISITS_DOCKER_IMAGE dockerhub $DOCKER_ID $DOCKER_TAG
                        '''
                    }
                } 
                stage('Build Api-gateway image for testing') {
                    when { changeset "spring-petclinic-api-gateway/**" }
                    agent { label "docker-agent-b" }
                    steps {
                        sh '''
                        sh scripts/devops/build_image.sh $APIGATEWAY_DOCKER_IMAGE dockerhub $DOCKER_ID $DOCKER_TAG
                        '''
                    }
                }
            }
        }
        stage('Push config & discovery'){
            parallel{
                stage('Push Config image for testing') {
                    when { changeset "spring-petclinic-config-server/**" }
                    agent { label "docker-agent-a" }
                    steps {
                        sh '''
                        docker login -u $DOCKER_ID -p $DOCKER_PASS
                        docker push $DOCKER_ID/$CONFIG_DOCKER_IMAGE-image:$DOCKER_TAG
                        '''
                    }
                }                
                stage('Push Discovery image for testing') {
                    when { changeset "spring-petclinic-discovery-server/**" }
                    agent { label "docker-agent-b" }
                    steps {
                        sh '''
                        docker login -u $DOCKER_ID -p $DOCKER_PASS
                        docker push $DOCKER_ID/$DISCOVERY_DOCKER_IMAGE-image:$DOCKER_TAG
                        '''
                    }
                }
            }
        }
        stage('Push customers & vets'){
            parallel {
                stage('Push Customers image for testing') {
                    when { changeset "spring-petclinic-customers-service/**" }
                    agent { label "docker-agent-a" }
                    steps {
                        sh '''
                        docker login -u $DOCKER_ID -p $DOCKER_PASS
                        docker push $DOCKER_ID/$CUSTOMERS_DOCKER_IMAGE-image:$DOCKER_TAG
                        '''
                    }
                }
                stage('Push Vets image for testing') {
                    when { changeset "spring-petclinic-vets-service/**" }
                    agent { label "docker-agent-b" }
                    steps {
                        sh '''
                        docker login -u $DOCKER_ID -p $DOCKER_PASS
                        docker push $DOCKER_ID/$VETS_DOCKER_IMAGE-image:$DOCKER_TAG
                        '''
                    }
                }
            }
        }
        stage('Push visits & api-gateway'){
            parallel{
                stage('Push Visits image for testing') {
                    when { changeset "spring-petclinic-visits-service/**" }
                    agent { label "docker-agent-a" }
                    steps {
                        sh '''
                        docker login -u $DOCKER_ID -p $DOCKER_PASS
                        docker push $DOCKER_ID/$VISITS_DOCKER_IMAGE-image:$DOCKER_TAG
                            '''
                    }
                }
                stage('Push Api-Gateway image for testing') {
                    when { changeset "spring-petclinic-api-gateway/**" }
                    agent { label "docker-agent-b" }
                    steps {
                        sh '''
                        docker login -u $DOCKER_ID -p $DOCKER_PASS
                        docker push $DOCKER_ID/$APIGATEWAY_DOCKER_IMAGE-image:$DOCKER_TAG
                        '''
                    }
                }
            }
        }
        // Déploiement de MYSQL sur l'environnement de TESTING si pas encore fait.
        // Uniquement utilise on veut utiliser mysql en tant que container dans EKS
        /*
        stage('Check/install MySQL in testing'){
            steps {
                container('helm') { 
                    script {
                        try {
                            sh '''
                            # Mysql deployment if its not already deployed
                            helm status mysql-server -n testing
                            '''
                        } catch (err) {
                            echo "Message: ${err}"
                            echo "Deploying mysql in testing ns .."
                            sh '''
                            cp kubernetes/helm/mysql-server/values.yaml values.yml
                            helm upgrade --install mysql-server kubernetes/helm/mysql-server --values=values.yml --create-namespace --namespace $NS 
                            '''
                        }
                    }
                }
            }
        }
        */
        // Check MYSQL AWS RDS availability
        stage('MySQL RDS accessibility') {
            agent { label "docker-agent-b" }
            steps {
                sh '''
                # Update RDS URL
                sed -i "s+host = .*+host = ${AWS_MYSQL_RDS}+g" scripts/devops/db-tools/my.cnf   
                echo "Mysql confi file:"
                cat scripts/devops/db-tools/my.cnf                 
                ./scripts/devops/db-tools/test_db_connection.sh
                '''
            }
        }
        stage("Deploy config & discorvery in testing"){
            parallel {
                stage('Deploy Config app in testing') {
                    when { changeset "spring-petclinic-config-server/**" }
                    steps {
                        container('helm') { 
                            sh '''
                            # Config Server deployment
                            cp kubernetes/helm/config-server/values.yaml values.yml
                            sed -i "s+tag.*+tag: ${DOCKER_TAG}+g" values.yml                    
                            helm upgrade --install config-server kubernetes/helm/config-server --values=values.yml --create-namespace --namespace $NS
                            '''
                        }
                    }
                }
                stage('Deploy Discovery app in testing') {
                    when { changeset "spring-petclinic-discovery-server/**" }
                    steps {
                        container('helm') { 
                            sh '''
                            # Discovery Server deployment
                            cp kubernetes/helm/discovery-server/values.yaml values.yml
                            sed -i "s+tag.*+tag: ${DOCKER_TAG}+g" values.yml
                            helm upgrade --install discovery-server kubernetes/helm/discovery-server --values=values.yml --create-namespace --namespace $NS
                            '''
                        }
                    }
                }
            }
        }
        stage("Deploy customers & vets in testing"){
            parallel {
                stage('Deploy Customers app in testing') {
                    when { changeset "spring-petclinic-customers-service/**" }
                    steps {
                        container('helm') { 
                            sh '''
                            # Customers Service deployment
                            cp kubernetes/helm/customers-service/values.yaml values.yml
                            sed -i "s+tag.*+tag: ${DOCKER_TAG}+g" values.yml                    
                            helm upgrade --install customers-service kubernetes/helm/customers-service --values=values.yml --create-namespace --namespace $NS
                            '''
                        }
                    }
                }
                stage('Deploy Vets app in testing') {
                    when { changeset "spring-petclinic-vets-service/**" }
                    steps {
                        container('helm') { 
                            sh '''
                            # Vets Service deployment
                            cp kubernetes/helm/vets-service/values.yaml values.yml
                            sed -i "s+tag.*+tag: ${DOCKER_TAG}+g" values.yml                    
                            helm upgrade --install vets-service kubernetes/helm/vets-service --values=values.yml --create-namespace --namespace $NS
                            '''
                        }
                    }
                }
            }
        }        
        stage("Deploy visits & admin in testing"){
            parallel {
                stage('Deploy Visits app in testing') {
                    when { changeset "spring-petclinic-visits-service/**" }
                    steps {
                        container('helm') { 
                            sh '''
                            # Visits Service deployment
                            cp kubernetes/helm/visits-service/values.yaml values.yml
                            sed -i "s+tag.*+tag: ${DOCKER_TAG}+g" values.yml                    
                            helm upgrade --install visits-service kubernetes/helm/visits-service --values=values.yml --create-namespace --namespace $NS
                            '''
                        }
                    }
                }
                stage('Deploy Api-gateway app in testing') {
                    when { changeset "spring-petclinic-api-gateway/**" }
                    steps {
                        container('helm') { 
                            sh '''
                            # Api Gateway deployment
                            cp kubernetes/helm/api-gateway/values.yaml values.yml
                            sed -i "s+tag.*+tag: ${DOCKER_TAG}+g" values.yml   
                            sed -i "s+traefik.ingress.kubernetes.io/router.middlewares.*+traefik.ingress.kubernetes.io/router.middlewares: $MIDDLEWARE_NS-services-strip@kubernetescrd+g" kubernetes/helm/api-gateway/templates/ingress.yaml
                            sed -i "s+.*secretName.*+    - secretName: testing-secret+g" kubernetes/helm/api-gateway/templates/ingress.yaml
                            sed -i "s+.*host: .*+  - host: testing.app-petclinic.cloudns.ph+g" kubernetes/helm/api-gateway/templates/ingress.yaml
                            sed -i "s+.*prod.app-petclinic.cloudns.ph+        - testing.app-petclinic.cloudns.ph+g" kubernetes/helm/api-gateway/templates/ingress.yaml 
                            cat kubernetes/helm/api-gateway/templates/ingress.yaml                 
                            helm upgrade --install api-gateway kubernetes/helm/api-gateway --values=values.yml --create-namespace --namespace $NS
                            '''
                        }
                    }
                }
            }
        }
        stage('Api-gateway accessibility in testing') {
            parallel{
                stage('Accessibility testing on agent-a') {
                    agent { label "docker-agent-a" }
                    steps {
                        sh '''
                        sleep 20
                        #./scripts/devops/test_accessibilite.sh http://api-gateway:8080
                        ./scripts/devops/test_accessibilite.sh https://testing.app-petclinic.cloudns.ph/
                        '''
                    }
                }
                stage('Accessibility testing on agent-b') {
                    agent { label "docker-agent-b" }
                    steps {
                        agent { label "docker-agent-b" }
                        sh '''
                        sleep 20
                        #./scripts/devops/test_accessibilite.sh http://api-gateway:8080
                        ./scripts/devops/test_accessibilite.sh https://testing.app-petclinic.cloudns.ph/
                        '''
                    }
                }
            }
        }
    }
}

 
                   